#!/bin/bash

if [ -z "$DOCKER_VOLUMES" ]; then
    echo 'Error: the DOCKER_VOLUMES environment variable is empty.'
    exit 1
fi

tar-volume () {
    PARENT_DIRECTORY="$(dirname "$1")"
    DIRECTORY_NAME="$(basename "$1")"
    mkdir -p "/home/output/archived-volumes/${PARENT_DIRECTORY}"
    echo "Creating volume archive at /home/output/archived-volumes/${PARENT_DIRECTORY}/${DIRECTORY_NAME}.tar.gz"
    tar -zcvf "/home/output/archived-volumes/${PARENT_DIRECTORY}/${DIRECTORY_NAME}.tar.gz" "$1"
}

for VOLUME_PATH in $DOCKER_VOLUMES;
do
    tar-volume $VOLUME_PATH
done
